<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Aurora.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Aurora.Core/Aurora.Core.csproj" />
    <ProjectReference Include="../Aurora.Adapters/Aurora.Adapters.csproj" />
  </ItemGroup>
</Project>
