using System.Globalization;
using Aurora.Adapters.Persistence;
using Aurora.Core.Abstractions;
using Aurora.Core.Contracts;
using Microsoft.Data.Sqlite;

namespace Aurora.Adapters.Cognition;

/// <summary>
/// The governed cognitive cycle (RFC 021).
/// </summary>
/// <remarks>
/// The point of this class is refusal. Every stage is recorded, no stage may be jumped over without
/// a reason, a result carrying state or an effect cannot be produced before Decision and Policy, an
/// effect cannot be marked without an allowing policy, and a cycle that executed cannot close
/// without Observation and Reflection.
/// <para>
/// The RFC's rationale says it plainly: the cycle exists so that a sentence generated by a model
/// cannot become an action or a memory. Refusals are how that is enforced rather than hoped for.
/// </para>
/// </remarks>
public sealed class SqliteCognitiveCycle : ICognitiveCycle
{
    private readonly SqliteConnectionFactory _factory;
    private readonly IClock _clock;

    public SqliteCognitiveCycle(SqliteConnectionFactory factory, IClock clock)
    {
        _factory = factory;
        _clock = clock;
    }

    public async Task<CognitiveCycle> RunAsync(CycleIngress ingress, CancellationToken ct)
    {
        var cycle = new CognitiveCycle(
            Guid.NewGuid().ToString("N"), ingress.WorkItemId, CycleStage.Perception,
            CycleStatus.Running, ingress.IngressRef, ingress.McpSessionRef,
            Iso(_clock.UtcNow), ingress.DeadlineAtUtc, CompletedAtUtc: null, Executed: false);

        await ExecuteAsync("""
            INSERT INTO cognitive_cycle
                (id, work_item_id, stage, status, ingress_ref, mcp_session_ref,
                 started_at_utc, deadline_at_utc, completed_at_utc, executed)
            VALUES (@id, @w, @stage, @status, @ing, @mcp, @at, @deadline, NULL, 0);
            """, ct,
            ("@id", cycle.Id), ("@w", cycle.WorkItemId), ("@stage", cycle.Stage),
            ("@status", cycle.Status), ("@ing", cycle.IngressRef),
            ("@mcp", (object?)cycle.McpSessionRef ?? DBNull.Value),
            ("@at", cycle.StartedAtUtc),
            ("@deadline", (object?)cycle.DeadlineAtUtc ?? DBNull.Value)).ConfigureAwait(false);

        return cycle;
    }

    public Task<CycleStageRecord> AdvanceAsync(
        string cycleId, string stage, IReadOnlyList<string> inputRefs,
        IReadOnlyList<string> outputRefs, string? decisionRef, CancellationToken ct) =>
        RecordAsync(cycleId, stage, inputRefs, outputRefs, decisionRef, StageStatus.Done, null, ct);

    public Task<CycleStageRecord> OmitAsync(
        string cycleId, string stage, string reason, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(reason))
        {
            // Rule 1 allows an omission only with its reason. An empty reason is a skipped stage
            // wearing a label.
            throw new CognitiveCycleException("An omitted stage must record why it was omitted.");
        }

        return RecordAsync(cycleId, stage, [], [], null, StageStatus.Omitted, reason, ct);
    }

    public async Task<CognitiveCycle> MarkExecutedAsync(
        string cycleId, bool policyAllowed, bool approvalSatisfied, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);
        IReadOnlyList<CycleStageRecord> stages = await StagesAsync(cycleId, ct).ConfigureAwait(false);

        // Rule 3: an effect happens after policy evaluation and, where required, a persisted
        // approval. Not "usually", not "when the caller remembers".
        if (!stages.Any(s => s.Stage == CycleStage.Policy && s.Status == StageStatus.Done))
        {
            throw new CognitiveCycleException(
                "A capability effect requires the Policy stage to have run.");
        }

        if (!policyAllowed)
        {
            throw new CognitiveCycleException("Policy did not allow this effect.");
        }

        if (!approvalSatisfied)
        {
            throw new CognitiveCycleException("The required approval is not satisfied.");
        }

        await ExecuteAsync("UPDATE cognitive_cycle SET executed = 1 WHERE id = @id;", ct,
            ("@id", cycleId)).ConfigureAwait(false);

        return cycle with { Executed = true };
    }

    public async Task<CycleResult> CompleteAsync(
        string cycleId, bool carriesPersistentStateOrExecution, string summary, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);
        IReadOnlyList<CycleStageRecord> stages = await StagesAsync(cycleId, ct).ConfigureAwait(false);

        // Rule 2: a result carrying persistent state or an execution result may only be produced
        // after Decision and Policy. This is the rule that stops a generated sentence becoming an
        // outcome without ever being decided on.
        if (carriesPersistentStateOrExecution)
        {
            foreach (var required in new[] { CycleStage.Decision, CycleStage.Policy })
            {
                if (!stages.Any(s => s.Stage == required && s.Status == StageStatus.Done))
                {
                    throw new CognitiveCycleException(
                        $"A result carrying state or an execution requires the {required} stage to have run.");
                }
            }
        }

        // Rule 5: observation and reflection are mandatory after an execution, even when reflection
        // concludes there is nothing to learn. "Nothing happened worth noting" is itself a record.
        if (cycle.Executed)
        {
            foreach (var required in new[] { CycleStage.Observation, CycleStage.Reflection })
            {
                if (!stages.Any(s => s.Stage == required))
                {
                    throw new CognitiveCycleException(
                        $"A cycle that executed cannot close without the {required} stage.");
                }
            }
        }

        var completedAt = Iso(_clock.UtcNow);
        await ExecuteAsync(
            "UPDATE cognitive_cycle SET status = @s, completed_at_utc = @at WHERE id = @id;", ct,
            ("@s", CycleStatus.Completed), ("@at", completedAt), ("@id", cycleId)).ConfigureAwait(false);

        return new CycleResult(cycleId, CycleStatus.Completed, carriesPersistentStateOrExecution, summary);
    }

    public async Task<CognitiveCycle> WaitAsync(string cycleId, string reason, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);

        await ExecuteAsync("UPDATE cognitive_cycle SET status = @s WHERE id = @id;", ct,
            ("@s", CycleStatus.Waiting), ("@id", cycleId)).ConfigureAwait(false);

        await RecordNoteAsync(cycleId, cycle.Stage, $"waiting: {reason}", ct).ConfigureAwait(false);

        return cycle with { Status = CycleStatus.Waiting };
    }

    public async Task<CognitiveCycle> ResumeAsync(string cycleId, string trigger, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);

        // Idempotent by design: an interrupted cycle may be resumed more than once, and resuming a
        // running one must not disturb it.
        if (cycle.Status is CycleStatus.Completed or CycleStatus.Failed or CycleStatus.Cancelled)
        {
            throw new CognitiveCycleException($"A {cycle.Status} cycle is not resumed.");
        }

        if (cycle.Status == CycleStatus.Running)
        {
            return cycle;
        }

        await ExecuteAsync("UPDATE cognitive_cycle SET status = @s WHERE id = @id;", ct,
            ("@s", CycleStatus.Running), ("@id", cycleId)).ConfigureAwait(false);

        return cycle with { Status = CycleStatus.Running };
    }

    public async Task<CognitiveCycle> FailAsync(string cycleId, string reason, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);

        await ExecuteAsync(
            "UPDATE cognitive_cycle SET status = @s, completed_at_utc = @at WHERE id = @id;", ct,
            ("@s", CycleStatus.Failed), ("@at", Iso(_clock.UtcNow)), ("@id", cycleId)).ConfigureAwait(false);

        await RecordNoteAsync(cycleId, cycle.Stage, $"failed: {reason}", ct).ConfigureAwait(false);

        return cycle with { Status = CycleStatus.Failed };
    }

    public async Task<CognitiveCycle?> GetAsync(string cycleId, CancellationToken ct)
    {
        await using SqliteConnection connection = await _factory.OpenAsync(ct).ConfigureAwait(false);
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT id, work_item_id, stage, status, ingress_ref, mcp_session_ref,
                   started_at_utc, deadline_at_utc, completed_at_utc, executed
              FROM cognitive_cycle WHERE id = @id;
            """;
        command.Parameters.AddWithValue("@id", cycleId);

        await using var reader = await command.ExecuteReaderAsync(ct).ConfigureAwait(false);
        if (!await reader.ReadAsync(ct).ConfigureAwait(false))
        {
            return null;
        }

        return new CognitiveCycle(
            reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetString(3),
            reader.GetString(4), reader.IsDBNull(5) ? null : reader.GetString(5),
            reader.GetString(6), reader.IsDBNull(7) ? null : reader.GetString(7),
            reader.IsDBNull(8) ? null : reader.GetString(8), reader.GetInt32(9) == 1);
    }

    public async Task<IReadOnlyList<CycleStageRecord>> StagesAsync(string cycleId, CancellationToken ct)
    {
        await using SqliteConnection connection = await _factory.OpenAsync(ct).ConfigureAwait(false);
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT cycle_id, stage, input_refs, output_refs, decision_ref,
                   started_at_utc, ended_at_utc, status, note
              FROM cycle_stage_record WHERE cycle_id = @id;
            """;
        command.Parameters.AddWithValue("@id", cycleId);

        var rows = new List<CycleStageRecord>();
        await using var reader = await command.ExecuteReaderAsync(ct).ConfigureAwait(false);
        while (await reader.ReadAsync(ct).ConfigureAwait(false))
        {
            rows.Add(new CycleStageRecord(
                reader.GetString(0), reader.GetString(1),
                Split(reader.GetString(2)), Split(reader.GetString(3)),
                reader.IsDBNull(4) ? null : reader.GetString(4),
                reader.GetString(5), reader.IsDBNull(6) ? null : reader.GetString(6),
                reader.GetString(7), reader.IsDBNull(8) ? null : reader.GetString(8)));
        }

        return rows.OrderBy(r => CycleStage.IndexOf(r.Stage)).ToList();
    }

    // ---- internals ----

    private async Task<CycleStageRecord> RecordAsync(
        string cycleId, string stage, IReadOnlyList<string> inputRefs, IReadOnlyList<string> outputRefs,
        string? decisionRef, string status, string? note, CancellationToken ct)
    {
        CognitiveCycle cycle = await Require(cycleId, ct).ConfigureAwait(false);

        if (cycle.Status is CycleStatus.Completed or CycleStatus.Failed or CycleStatus.Cancelled)
        {
            throw new CognitiveCycleException($"A {cycle.Status} cycle records no further stages.");
        }

        var index = CycleStage.IndexOf(stage);
        if (index < 0)
        {
            throw new CognitiveCycleException($"'{stage}' is not a stage of the cycle.");
        }

        IReadOnlyList<CycleStageRecord> existing = await StagesAsync(cycleId, ct).ConfigureAwait(false);

        // No stage is jumped over. Anything earlier must have run or been omitted with a reason,
        // which is what makes "did this cycle skip Decision?" answerable from the record alone.
        for (var i = 0; i < index; i++)
        {
            var earlier = CycleStage.Order[i];
            if (!existing.Any(s => s.Stage == earlier))
            {
                throw new CognitiveCycleException(
                    $"Cannot advance to {stage}: {earlier} has neither run nor been omitted.");
            }
        }

        var now = Iso(_clock.UtcNow);
        var record = new CycleStageRecord(
            cycleId, stage, inputRefs, outputRefs, decisionRef, now, now, status, note);

        await ExecuteAsync("""
            INSERT INTO cycle_stage_record
                (id, cycle_id, stage, input_refs, output_refs, decision_ref,
                 started_at_utc, ended_at_utc, status, note)
            VALUES (@id, @c, @stage, @in, @out, @dec, @start, @end, @status, @note)
            ON CONFLICT(cycle_id, stage) DO UPDATE SET
                input_refs = excluded.input_refs, output_refs = excluded.output_refs,
                decision_ref = excluded.decision_ref, ended_at_utc = excluded.ended_at_utc,
                status = excluded.status, note = excluded.note;
            """, ct,
            ("@id", Guid.NewGuid().ToString("N")), ("@c", cycleId), ("@stage", stage),
            ("@in", string.Join(',', inputRefs)), ("@out", string.Join(',', outputRefs)),
            ("@dec", (object?)decisionRef ?? DBNull.Value), ("@start", now), ("@end", now),
            ("@status", status), ("@note", (object?)note ?? DBNull.Value)).ConfigureAwait(false);

        await ExecuteAsync("UPDATE cognitive_cycle SET stage = @stage WHERE id = @id;", ct,
            ("@stage", stage), ("@id", cycleId)).ConfigureAwait(false);

        return record;
    }

    private Task RecordNoteAsync(string cycleId, string stage, string note, CancellationToken ct) =>
        ExecuteAsync("UPDATE cycle_stage_record SET note = @n WHERE cycle_id = @c AND stage = @s;", ct,
            ("@n", note), ("@c", cycleId), ("@s", stage));

    private async Task<CognitiveCycle> Require(string cycleId, CancellationToken ct) =>
        await GetAsync(cycleId, ct).ConfigureAwait(false)
        ?? throw new CognitiveCycleException("Unknown cycle.");

    private async Task ExecuteAsync(string sql, CancellationToken ct, params (string Name, object Value)[] args)
    {
        await using SqliteConnection connection = await _factory.OpenAsync(ct).ConfigureAwait(false);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        foreach ((var name, var value) in args)
        {
            command.Parameters.AddWithValue(name, value);
        }

        await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private static IReadOnlyList<string> Split(string value) =>
        value.Split(',', StringSplitOptions.RemoveEmptyEntries);

    private static string Iso(DateTimeOffset value) => value.ToString("O", CultureInfo.InvariantCulture);
}
